### ISSUE TITLE
problem of compiling this code under windows platform

### ISSUE THREAD

**Issue by hushanming** [nmoehrle/mvs-texturing#50]
Hi Nils,
These days I compile your code of mvs-texturing on windows platform,but there is little problems.Since msvc support openmp2.0, but your code, there are details about openmp3.0 or higher.The code is as follows:
void
generate_texture_atlases(std::vector<TexturePatch::Ptr> * orig_texture_patches,
    std::vector<TextureAtlas::Ptr> * texture_atlases) {

    std::list<TexturePatch::ConstPtr> texture_patches;
    while (!orig_texture_patches->empty()) {
        //TODO avoid copying
        texture_patches.push_back(orig_texture_patches->back());
        orig_texture_patches->pop_back();
    }

    std::cout << "\tSorting texture patches... " << std::flush;
    /* Improve the bin-packing algorithm efficiency by sorting texture patches
     * in descending order of size. */
    texture_patches.sort(comp);
    std::cout << "done." << std::endl;

    std::size_t const total_num_patches = texture_patches.size();
    std::size_t remaining_patches = texture_patches.size();
    std::ofstream tty("/dev/tty", std::ios_base::out);

    #pragma omp parallel
    {
    #pragma omp single
    {

    while (!texture_patches.empty()) {
        unsigned int texture_size = calculate_texture_size(texture_patches);

        texture_atlases->push_back(TextureAtlas::create(texture_size));
        TextureAtlas::Ptr texture_atlas = texture_atlases->back();

        /* Try to insert each of the texture patches into the texture atlas. */
        std::list<TexturePatch::ConstPtr>::iterator it = texture_patches.begin();
        for (; it != texture_patches.end();) {
            std::size_t done_patches = total_num_patches - remaining_patches;
            int precent = static_cast<float>(done_patches)
                / total_num_patches * 100.0f;
            if (total_num_patches > 100
                && done_patches % (total_num_patches / 100) == 0) {

                tty << "\r\tWorking on atlas " << texture_atlases->size() << " "
                 << precent << "%... " << std::flush;
            }

            if (texture_atlas->insert(*it)) {
                it = texture_patches.erase(it);
                remaining_patches -= 1;
            } else {
                ++it;
            }
        }

        #pragma omp task
        texture_atlas->finalize();
    }

    std::cout << "\r\tWorking on atlas " << texture_atlases->size()
        << " 100%... done." << std::endl;
    util::WallTimer timer;
    std::cout << "\tFinalizing texture atlases... " << std::flush;
    #pragma omp taskwait
    std::cout << "done. (Took: " << timer.get_elapsed_sec() << "s)" << std::endl;

    /* End of single region */
    }
    /* End of parallel region. */
    }
}
It shows "task" should openmp directives name when I compile this code.So I ask this code (on task and taskwait) could use other instructions (openmp2.0) replace it?

**Comment by nmoehrle** [comment]
When I have an hour I will switch to `std::async` (instead of `omp task`) like [here](https://github.com/nmoehrle/rayint/blob/premake/apps/raycast/raycast.cpp#L166).
Until then you could use the intel compiler which supports OpenMP 3.0.

**Comment by hushanming** [comment]
Hi,I'm sorry I do not quite understand,can you explain a little more clear?

**Comment by hushanming** [comment]
Hi,Nils
Thank you for your reply, here there are other problems arise, I compile this code and it will display an internal  error has occured on the compiler, the code is as follows:
template <typename T, int M, int N> Eigen::Matrix<T,M,N>
mve_to_eigen(math::Matrix<T, M, N> const & mat) {
    Eigen::Matrix<T, M, N> ret;
    for (int m = 0; m < M; ++m)
        for (int n = 0; n < N; ++n)
            ret(m, n) = mat(m, n);
    return ret;
}

/**
 * Converts an MVE vector into an Eigen row vector.
 */
template <typename T, int N> Eigen::Matrix<T, 1, N>
mve_to_eigen(math::Vector<T, N> const & vec) {
    Eigen::Matrix<T, 1, N> ret;
    for (int n = 0; n < N; ++n)
        ret(0, n) = vec(n);
    return ret;
}
When I call this code, the compiler will display an error， do you have any views on it?

**Comment by nmoehrle** [comment]
Please use markdown to distinguish code from normal text, else wise important parts (such as template parameters) are rendered incorrectly. You can find a markdown cheat sheet [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

The code itself is correct but contains templates as well as operator overloading which might be causing trouble. Can you please show me the compiler output (also formatted as code block) and which compiler you are using.

**Comment by nmoehrle** [comment]
Commit 1e4432c implements the change from `omp task` to `std::async` which should make the code OpenMP 2.0 compliant.

**Comment by hushanming** [comment]
Hi,
I'm sorry my description of the problem is not clear enough, the compiler I'm using is vs2013,and the error is as follows:

D:\vs2010\mvs-texturing\mvs-texturing-master\libs\tex\calculate_data_costs.cpp(102): fatal error C1001: An internal error has occurred in the compiler.
7>  (compiler file “msc1.cpp”，line 1325) To work around this problem, try simplifying or changing the program near the locations listed above. Please choose the Technical Support command on the Visual C++ Help menu, or open the Technical Support help file for more information

-----Build started: Project: textrecon, Configuration: Debug x64

**Comment by nmoehrle** [comment]
The compiler is referring to a [line](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/calculate_data_costs.cpp#L102) that does not contain a call to` mve_to_eigen` or am I wrong?

There is however a style error in that line
```
    is_inlier[row] = (gauss_value >= gauss_rejection_threshold ? 1 : 0);
```
it should be
```
    is_inlier[row] = (gauss_value >= gauss_rejection_threshold) ? 1 : 0;
```

**Comment by hushanming** [comment]
In my computer errors in this line

  double gauss_value = multi_gauss_unnormalized(color, var_mean, covariance_inv);

This line of code in your top line（line 101）

**Comment by hushanming** [comment]
In my computer errors in this [line](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/calculate_data_costs.cpp#L101)

**Comment by hushanming** [comment]
I'm sorry to disturbing you,because of my question is unclear,I will detail my problem
In the begining I found the solution about the error in this [line](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/calculate_data_costs.cpp#L63) is to update my vs2013 , but when I updated it still shows the same error in this [line](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/calculate_data_costs.cpp#L101),these errors are all about
_fatal error C1001: An internal error has occurred in the compiler._ .
I found a lot of information in this area, but still have no clue.So I would like to ask your opinion about this error.Thank you!

**Comment by nmoehrle** [comment]
There are two things you could try:
- manually inlining the function
- manually specifying the template arguments

**Comment by xialang2012** [comment]
You should change to VS2015.

**Comment by xialang2012** [comment]
Some errors occurred about the https://github.com/nmoehrle/mvs-texturing/tree/switch-to-openmp-2 on VS2015 when built it

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3016	'vertex_idx': index variable in OpenMP 'for' statement must have signed integral type	mrf	mvs-texturing\libs\mrf\lbp_graph.cpp	23	
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3016	'queue_id': index variable in OpenMP 'for' statement must have signed integral type	tex	mvs-texturing\libs\tex\partition_mesh.cpp	173

**Comment by nmoehrle** [comment]
@andre-schulz has a fork which should build under windows, however it is a few commits behind.
Several of the issues described here have been fixed previously with https://github.com/andre-schulz/mvs-texturing/commit/99ca13856455291765616c727ebcbc82f136ead6.

**Comment by xialang2012** [comment]
Yes, this one can be built with VS 2015 well.

**Comment by xialang2012** [comment]
I have tried Intel ICC 16 on windows, it still faces some challenges. Besides, although the windows version provided by @andre-schulz can run well for the normal cases, it also has some problems. 

MVS-Textuing is a great open source tools for texturing the mesh, and we hope it can be more perfect as quickly as possible.

**Comment by hushanming** [comment]
Thank you for your reply,I know it's a challenge for me to put  this code ported to windows platform,and I know this process there will be many problems but I believe it's an excellent open-source code,and it will give me a lot help if I use it to learn texture mapping.This is my motivation to overcom diffculties.Thank you for providing open-source code.Thank you.
